### ISSUE TITLE
'ConcatDatasetBatchSampler' object has no attribute 'batch_size'

### ISSUE THREAD

**Issue by 2502912390** [Audio-WestlakeU/ATST-SED#23]
Traceback (most recent call last):
  File "1stage.py", line 441, in <module>
    single_run(
  File "1stage.py", line 339, in single_run
    trainer.fit(desed_training, ckpt_path=checkpoint_resume)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 206, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1528, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 284, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 158, in _update_dataloader
    dl_args, dl_kwargs = _get_dataloader_init_args_and_kwargs(dataloader, sampler, mode)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 219, in _get_dataloader_init_args_and_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode, disallow_batch_sampler))
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 330, in _dataloader_init_kwargs_resolve_sampler
    batch_size=batch_sampler.batch_size,
AttributeError: 'ConcatDatasetBatchSampler' object has no attribute 'batch_size'
您好，想请问这个怎么解决？已经困扰我很久了，使用的是dcase2024环境，已经将utils中的from sed_scores_eval.utils.scores import create_score_dataframe改为from sed_scores_eval.base_modules.scores import create_score_dataframe；
奇怪的是
batch_sizes = config["training"]["batch_size"]
samplers = [torch.utils.data.RandomSampler(x) for x in tot_train_data]
batch_sampler = ConcatDatasetBatchSampler(samplers, batch_sizes)
desed_training = SEDTask4(
        config,
        encoder=encoder,
        sed_student=sed_student,
        opt=opt,
        train_data=train_dataset,
        valid_data=valid_dataset,
        test_data=test_dataset,
        train_sampler=batch_sampler,
        scheduler=exp_scheduler,
        fast_dev_run=fast_dev_run,
        evaluation=evaluation
    )
 与dcase2024任务baseline代码是完全一致的，dcase2024的baseline我可以跑通，但是这份代码不行，使用的同一个环境。

**Comment by SaoYear** [comment]
这是由于pytorch lightning的版本问题导致的。
具体问题为：
pytorch lightning在加载dataset时，为了保证使用者提供的dataset模块是torch符合dataset模块的API的，在加载dataset后，进行了参数的重查，也就是你报错部分的`dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode, disallow_batch_sampler))`的功能。
目前这个重查function已经在pytorch lightning2.4.X之后被写成了一个warning（因为他会导致莫名其妙的报错），所以你遇到这个问题是因为pytorchlightning版本的问题带来的，并不是整套算法的bug。

**Comment by 2502912390** [comment]
十分感谢！！！将pytorch lightning升级到2.4.0这个问题得到解决了
