### ISSUE TITLE
a little bug maybe "from sed_scores_eval.utils.scores import create_score_dataframe"

### ISSUE THREAD

**Issue by Kiri0824** [Audio-WestlakeU/ATST-SED#9]
congratulations! 
I‘m new to SED, i just got error in /train/local/utils.py. `ModuleNotFoundError: No module named 'sed_scores_eval.utils.scores'`
and i checked https://github.com/DCASE-REPO/DESED_task/blob/master/recipes/dcase2024_task4_baseline/local/utils.py  
the dcase2024, use `from sed_scores_eval.base_modules.scores import create_score_dataframe`
:)

**Comment by SaoYear** [comment]
Hi Kiri, 

Thanks for your interest!

Yeah I saw the version changes of the package `sed_scores_eval`. The DCASE 2024 baseline currently used `sed_scores_eval>=0.0.3` while the version in this repo is `sed-scores-eval=0.0.0`   following the 2023 baseline. 

I would not change the codes in this repo to ensure the reproduction of the reported results. But you could modify it according to your environment. 

Thanks for mentioning that, which might help others who use ATST-SED for the 2024 baseline.

Nian

**Comment by Kiri0824** [comment]
ok fine, thank you:), you reply so fast

**Comment by Osirising** [comment]
检查了一下sed_scores_eval，发现scores已经从ultis移到base_modules了，所以你仅仅需要将from sed_scores_eval.utils.score import create_score_dataframe改成from sed_scores_eval.base_modules.score import create_score_dataframe就ok了

**Comment by 2502912390** [comment]
Traceback (most recent call last):
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 206, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1528, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 284, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 158, in _update_dataloader
    dl_args, dl_kwargs = _get_dataloader_init_args_and_kwargs(dataloader, sampler, mode)
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 219, in _get_dataloader_init_args_and_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode, disallow_batch_sampler))
  File "/root/anaconda3/envs/dcase2024/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 330, in _dataloader_init_kwargs_resolve_sampler
    batch_size=batch_sampler.batch_size,
AttributeError: 'ConcatDatasetBatchSampler' object has no attribute 'batch_size'
我用的也是dcase2024的conda环境，请问你们有出现这个问题吗？
